{% set name = "smirnoffee" %}
{% set version = "0.0.1a1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: b4c5b39e8a03b75c4c25cb60d99031cbc410331e8d13ca44ec42608539767ff9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

    - openff-toolkit-base >=0.9.2
    - openff-units
    - openff-interchange ==0.1.0

    - pytorch

    - pydantic

test:
  imports:
    - smirnoffee

about:
  home: https://github.com/SimonBoothroyd/smirnoffee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Differentiably evaluate energies of molecules using SMIRNOFF force fields.
  description: |
    A framework that aims to offer a simple API for differentiably evaluating the energy
    of SMIRNOFF force fields applied to single molecules using pytorch.
  doc_url: https://github.com/SimonBoothroyd/smirnoffee
  dev_url: https://github.com/SimonBoothroyd/smirnoffee

extra:
  recipe-maintainers:
    - simonboothroyd
